### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by bzerangue** [vingorius/jade-beautify#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [jade-beautify](https://github.com/vingorius/jade-beautify) package, v0.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Users/bmz/.atom/packages/jade-beautify/lib/jade-beautify.js:37

TypeError: Cannot read property 'endsWith' of undefined
    at Object.jadeBeautify.isJadeFile (/Users/bmz/.atom/packages/jade-beautify/lib/jade-beautify.js:37:56)
    at atom-workspace.jadeBeautify.handleSaveEvent (/Users/bmz/.atom/packages/jade-beautify/lib/jade-beautify.js:42:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```
### Commands

```
  2x -0:07.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-jade, v0.3.0
atom-xsltransform, v0.8.0
compare-files, v0.6.2
editorconfig, v1.2.0
emmet, v2.3.12
jade-autocompile, v0.6.3
jade-beautify, v0.0.10
language-ace, v1.1.0
language-apache, v1.3.0
language-html-swig, v2.0.1
language-liquid, v0.4.0
language-swig, v0.1.4
language-twig, v1.6.2
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by vingorius** [comment]
@bzerangue Could you explain when It occur ? how can i reproduce this exception in my env.

**Comment by bzerangue** [comment]
I just started Atom and I tried to save a document and it would always
produce this error until I disabled jade-beautify.

**Comment by vingorius** [comment]
I patch it v0.0.11.
please check & feedback.
tks.

**Comment by rustanacexd** [comment]
I have this issue now using the latest version of atom in mac os x 10.10.5

**Comment by vingorius** [comment]
@rustanacexd  tell me jade-beautify version.

**Comment by newdaveespionage** [comment]
1. install jade-beautify
2. create a new file, try to save in plain text mode
3. error thrown, prevents save

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: [jade-beautify](https://github.com/vingorius/jade-beautify) package, v0.0.12

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Users/daveespionage/.atom/packages/jade-beautify/lib/jade-beautify.js:40

TypeError: Cannot read property 'endsWith' of undefined
    at Object.jadeBeautify.isJadeFile (/Users/daveespionage/.atom/packages/jade-beautify/lib/jade-beautify.js:40:36)
    at atom-workspace.jadeBeautify.handleSaveEvent (/Users/daveespionage/.atom/packages/jade-beautify/lib/jade-beautify.js:47:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:32.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:12.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.9.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:09.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.5.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:05.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:03.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
atom-jshint, v2.0.0
jade-beautify, v0.0.12
linter, v1.11.3
linter-jade, v0.3.2
linter-sass-lint, v0.6.3
minimap, v4.19.0
minimap-hide, v0.3.0
snippets-jade, v0.1.1
source-preview-babel, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by jerone** [comment]
@vingorius 

Solution: change https://github.com/vingorius/jade-beautify/blob/master/lib/jade-beautify.js#L39 with:

``` js
if (editor && editor.getPath())
```

**Comment by vingorius** [comment]
Tks @jerone.
