### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by madole** [vingorius/jade-beautify#3]
1. Install git-projects
2. Ctrl+Alt+O 
3. Jade Error appears

I know it sounds unrelated, but that's the reproducible steps 

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [jade-beautify](https://github.com/vingorius/jade-beautify) package, v0.0.11
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/andrew/.atom/packages/jade-beautify/lib/jade-beautify.js:37

TypeError: Cannot read property 'getPath' of undefined
  at Object.jadeBeautify.isJadeFile (/home/andrew/.atom/packages/jade-beautify/lib/jade-beautify.js:37:42)
  at atom-workspace.jadeBeautify.convert (/home/andrew/.atom/packages/jade-beautify/lib/jade-beautify.js:53:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  3x -0:42.9.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
     -0:01.0 jade-beautify:convert (div.incompatible-packages.padded.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-jade, v0.3.0
color-picker, v2.0.13
editor-stats, v0.17.0
editorconfig, v1.2.0
emmet, v2.3.13
file-icons, v1.6.9
formatter-coffeescript, v0.1.1
grunt-runner, v0.11.0
highlight-line, v0.11.0
jade-beautify, v0.0.11
javascript-snippets, v1.0.0
linter, v1.8.1
linter-coffeescript, v1.0.0
linter-stylint, v2.0.1
markdown-preview-plus, v2.2.0
minimap, v4.13.4
minimap-pigments, v0.1.7
pigments, v0.15.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by vingorius** [comment]
@madole  OK, Let me check.

**Comment by jerone** [comment]
Steps to reproduce same error (make sure `Force beautify on save` is enabled):
1. Open Settings panel.
2. Press Save.

_It happened by mistake :)_

Checking for existence of `getPath` [here](https://github.com/vingorius/jade-beautify/blob/d807eebd081b9e47f202a74ed50bf83f34600f30/lib/jade-beautify.js#L37) would solve this.

Related to https://github.com/vingorius/jade-beautify/issues/2

**Comment by vingorius** [comment]
I guess,it may be happened on Ubuntu or Mac.
And pointed out from @jerone, I'll change code like below.

if(atom.workspace.getActiveTextEditor() === undefined) return false;

In my ubuntu machine, i'll test it no far from now. but it's a long holiday!!!
